kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: psql-vote
  namespace: vote
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: netapp
  volumeMode: Filesystem
